[package]
name = "fyrox-template"
version = "0.36.2"
edition = "2021"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
license = "MIT"
description = "Command line interface for project template generator for Fyrox engine"
keywords = ["fyrox", "game", "project"]
categories = ["game-development"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
homepage = "https://fyrox.rs"
repository = "https://github.com/FyroxEngine/Fyrox"
readme = "README.md"
rust-version = "1.86"

[dependencies]
fyrox-template-core = { version = "0.36.2", path = "../template-core" }
clap = { version = "4", features = ["derive"] }