[package]
name = "rg3d-core"
version = "0.18.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Shared core for the rg3d engine and its external crates."
keywords = ["game", "engine", "3d"]
categories = ["game-development", "graphics", "gui", "rendering", "wasm"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
homepage = "https://rg3d.rs"
documentation = "https://docs.rs/rg3d-core"
repository = "https://github.com/mrDIMAS/rg3d"
readme = "README.md"
resolver = "2"

[dependencies]
rg3d-core-derive = { path = "../rg3d-core-derive", version = "0.13.0" }

base64 = "0.13.0"
byteorder = "1.4.3"
rand = "0.8.4"
memoffset = "0.6.4"
lazy_static = "1.4.0"
nalgebra = "0.29.0"
arrayvec = "0.7.1"
futures = {version = "0.3.16", features = ["thread-pool"] }
uuid = { version = "0.8.2", features = ["v4","wasm-bindgen"] }
instant = {version = "0.1.10", features = ["wasm-bindgen"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.53", features = ["Request", "Window", "Response", "AudioContext", "AudioBuffer", "AudioContextOptions", "AudioNode", "AudioBufferSourceNode", "AudioDestinationNode"] }
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.26"
js-sys = "0.3.53"

[features]
serde = ["nalgebra/serde-serialize"]
enable_profiler = []
