[package]
name = "rg3d-resource"
version = "0.1.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Asset management crate for rg3d engine"
keywords = ["asset", "resource"]
repository = "https://github.com/mrDIMAS/rg3d"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE"]
documentation = "https://docs.rs/rg3d-resource"

[dependencies]
rg3d-core = { path = "../rg3d-core", version = "0.17" }