[package]
name = "fyrox-build-tools"
version = "0.36.2"
edition = "2021"
license = "MIT"
description = "Build tools for Fyrox Engine"
keywords = ["build"]
categories = ["game-development"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
homepage = "https://fyrox.rs"
documentation = "https://docs.rs/fyrox-build-tools"
repository = "https://github.com/FyroxEngine/Fyrox"
rust-version = "1.86"

[dependencies]
fyrox-core = { path = "../fyrox-core", version = "0.36.2" }
fyrox-ui = { path = "../fyrox-ui", version = "0.36.2" }
fyrox-resource = { path = "../fyrox-resource", version = "0.36.2" }
serde = { version = "1.0.215", features = ["derive"] }