[package]
name = "fyrox-sound"
version = "0.30.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2021"
license = "MIT"
description = "Sound library for games."
keywords = ["sound", "game", "hrtf", "binaural", "reverb"]
categories = ["game-development", "multimedia::audio"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md", "/examples/*"]
homepage = "https://fyrox.rs"
documentation = "https://docs.rs/fyrox-sound"
repository = "https://github.com/FyroxEngine/Fyrox"
readme = "README.md"
resolver = "2"
rust-version = "1.56"

[dependencies]
fyrox-core = { path = "../fyrox-core", version = "0.23.0" }
fyrox-resource = { path = "../fyrox-resource", version = "0.7.0" }
lewton = "0.10.2"
hrtf = "0.8.0"
hound = "3.4.0"
strum = "0.24.0"
strum_macros = "0.24.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = {version = "0.3.9", features = ["minwindef", "winnt", "windef", "winuser", "dsound", "synchapi", "winbase" ] }

[target.'cfg(target_os = "linux")'.dependencies]
alsa-sys = { version = "0.3.1" }

[target.'cfg(target_os = "macos")'.dependencies]
coreaudio-sys = { version = "0.2.8" }
core-foundation-sys = { version = "0.8.2" }

[features]
enable_profiler = ["fyrox-core/enable_profiler"]
