[package]
name = "fyroxed"
license = "MIT"
version = "0.12.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2021"
rust-version = "1.56"
description = "A scene editor for Fyrox game engine"
homepage = "https://github.com/FyroxEngine/Fyrox"
keywords = ["fyrox", "editor", "rust"]
repository = "https://github.com/FyroxEngine/Fyrox"
readme = "README.md"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md", "/resources/**/*"]

[dependencies]
fyrox = { version = "0.25", path = ".." }
lazy_static = "1.4.0"
ron = "0.7.0"
serde = "^1.0.0"
toml = "0.5"
strum = "0.24.0"
strum_macros = "0.24.0"

[features]
enable_profiler = ["fyrox/enable_profiler"]
