[package]
name = "wasm"
version = "0.1.0"
authors = ["Dmitry <d1maxa@yandex.ru>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rg3d = { path = "../../" }

[dev-dependencies]
wasm-bindgen-test = "0.3"