[package]
name = "project-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { path = "../fyrox" }
fyrox-template-core = { version = "0.11.0", path = "../template-core" }
serde = { version = "1", features = ["derive"] }
ron = "0.8.1"
open = "5.0.1"